name: 'Setup Poetry'
description: 'This action installs and setups the poetry in current environment'
runs:
  using: "composite"
  steps:
    - run: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | python -
      shell: bash
    - run: echo "$HOME/.poetry/bin" >> $GITHUB_PATH
      shell: bash
    - run: make install
      shell: bash
